version: '3.8'

services:
  telegram-downloader:
    build:
      context: .
      args:
        - UID=${UID:-1000} # passes UID and GID to the container from .env
        - GID=${GID:-1000}
    container_name: telegram-downloader
    env_file:
      - .env
    volumes:
      # - ./downloader_session.session:/app/downloader_session.session  # Persist Telegram session
      # - ${DOWNLOAD_BASE_PATH}:${DOWNLOAD_BASE_PATH}
      # - HOST_PATH:CONTAINER_PATH
      - type: bind
        source: ./downloader_session.session #host path
        target: /app/downloader_session.session #container path
      - type: bind
        source: ${DOWNLOAD_BASE_PATH}
        target: ${DOWNLOAD_BASE_PATH} #they are same because actual files are downloaded in this path

    restart: unless-stopped


    # user: "${UID}:${GID}"
    # stdin_open: true  # Keep STDIN open
    # tty: true        # Allocate a pseudo-TTY
    # restart: "no"    # Don't restart automatically since we need user input
